# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20161024_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='tags',
            field=models.CharField(max_length=50),
        ),
    ]
