# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_auto_20161024_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(),
        ),
    ]
